In [ ]:
import pandas as pd
import re

base = pd.read_excel('C:/Users/novo1/OneDrive/Desktop/Dev/hrcomiss/venda-mensal-bruta_colab-bi_2025-08-21.xlsx')

base_columns = ['ID orçamento', 'Data orçamento', 'Status', 'Revenda', 'Data venda','Mês venda', 'Unidade','Avaliador', 'Valor líquido','ID cliente']

base = base[base_columns]

base = base.loc[base['Status'] == "Finalizado"]

base = base.loc[~base['Avaliador'].isna()]

base['Valor líquido'] = base['Valor líquido'].fillna(0)

base = base.loc[base['Unidade'] != 'PRAIA GRANDE']

def remover_parenteses(nome):
    return re.sub(r'\s*\(.*\)', '', nome).strip()

base['avaliadora_padronizada'] = base['Avaliador'].apply(remover_parenteses)

base['avaliadora_padronizada'] = base['avaliadora_padronizada'].replace("AMANDA SOUZA FAIOLI GRU","AMANDA SOUZA FAIOLI")

# base = base.loc[base['Avaliador'].str.contains("gru",case=False)]

base['avaliadora_padronizada'] = base['avaliadora_padronizada'].str.upper()

groupby_revenda = base.groupby(['avaliadora_padronizada']).agg({"Unidade" : 'unique','Valor líquido' : 'sum'}).reset_index()

groupby_revenda = groupby_revenda.sort_values(by=['Valor líquido'],ascending=False).reset_index(drop=True)

groupby_revenda

                 avaliadora_padronizada           Unidade  Valor líquido
0                KARINE OLIVEIRA SANTOS           [MOEMA]       95734.97
1                   JULIA MACENA DANTAS            [LAPA]       84460.00
2    GABRIELA GOMES MAGALHAES DOS ANJOS     [SANTO AMARO]       80774.89
3                SIMONE CROCCI FERREIRA  [MOEMA, JARDINS]       77782.10
4                   ELOIZA KARYNA ZONHO         [TATUAPÉ]       73535.96
..                                  ...               ...            ...
116             INGRID COSTA DE ANDRADE            [LAPA]         270.00
117               CLEIDIANE SOUSA COSTA        [CAMPINAS]          90.00
118               INGRID VIDAL DA SILVA         [JARDINS]          90.00
119               KELLY APARECIDA LEITE         [TATUAPÉ]          90.00
120                     CINTIA DOS REIS         [JARDINS]           0.00

[121 rows x 3 columns]